### ISSUE TITLE
Onboarding Request: rCAX

### ISSUE THREAD

**Issue by eeholmes** [noaa-fisheries-integrated-toolbox/onboard-and-update#10]
### Active Development

Yes

### Tool name

rCAX: R client for the Coordinated Assessment Program CAX database REST API

### Tool abbreviation

rCAX

### Author(s)

Elizabeth Holmes and Mari Williams

### NOAA Internal

Yes

### Maintainer Name

Elizabeth Holmes

### Maintainer Email

eli.holmes@noaa.gov

### Background Text

rCAX is an R client for the [Coordinated Assessments API](https://www.streamnet.org/resources/exchange-tools/rest-api-documentation/). Coordinated Assessments data eXchange (CAX) is developed by the Coordinated Assessments Partnership (CAP). CAP is a collaborative process to efficiently share and provide access to standardized derived information, such as fish population-scale high-level indicators (HLIs) and supporting metrics. Participants in CAP include state fish and wildlife management agencies, tribes, federal agencies such as National Oceanic and Atmospheric Administration Fisheries (NOAA Fisheries) and Bonneville Power Administration (BPA), and others. CAP is co-sponsored by StreamNet and Pacific Northwest Aquatic Monitoring Partnership (PNAMP). Make sure to review the [StreamNet Terms of Use](https://nwfsc-math-bio.github.io/rCAX/articles/terms.html) for these data, the [StreamNet Data Policy](https://www.streamnet.org/resources/exchange-tools/data-agreements/) and the citation information from [StreamNet](https://www.streamnet.org/resources/citing-sn/) and [PNAMP](https://www.pnamp.org/project/data-citation-and-attribution) for database queries.

### Citation

https://doi.org/10.5281/zenodo.7402463

### References

Holmes EE, Williams M (2023). “rCAX: Coordinated Assessments REST API R Client. R package version 1.0.1.” NOAA Fisheries, Northwest Fisheries Science Center, Math Bio Program. [doi:10.5281/zenodo.7402463](https://doi.org/10.5281/zenodo.7402463).

### Associated Tools

pycax

### User Organizations

NOAA Northwest Fisheries Science Center

### Website Link

https://nwfsc-math-bio.github.io/rCAX

### Documentation Link

https://nwfsc-math-bio.github.io/rCAX

### Source Code Link

https://github.com/nwfsc-math-bio/rCAX

### Software Badges

[![github](https://img.shields.io/github/v/release/nwfsc-math-bio/rCAX?color=brightgreen&label=GitHub)](https://github.com/nwfsc-math-bio/rCAX/releases/latest)
[![check-release](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml/badge.svg)](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml)

### Toolbox Drawers

- [ ] Ecosystems
- [x] Fish and Fisheries
- [ ] Human Dimensions
- [x] Protected Species
- [ ] General Modeling and Productivity Tools

### Keywords

- [ ] ADMB
- [ ] Age Structured Model
- [ ] Bayesian Modeling
- [ ] Bycatch
- [ ] C++
- [ ] Calculator
- [ ] Data Exploration
- [ ] Data Limited Method
- [ ] Data Visualization
- [ ] Decision Support Tool
- [ ] Developer Utilities
- [ ] Economics
- [ ] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [ ] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [ ] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [ ] Natural Mortality Model
- [ ] NOAA Branding
- [ ] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [X] R Package
- [ ] Reference Points Model
- [ ] Risk Assessment Tool
- [X] Salmon
- [ ] Sampling Decision Tool
- [ ] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [ ] Spatial Model
- [ ] Species Distribution Model
- [X] Standardized Reporting
- [ ] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [ ] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [ ] Web App

### Uses Github Releases

Yes

### Comments

would be good to add "API client", "data access", and "database" to the list of topics

Link for issues and discussions (GitHub) would be good.

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "rCAX: R client for the Coordinated Assessment HLI API",
  "tool_abbreviation": "rCAX",
  "authors": "Elizabeth Holmes and Mari Williams",
  "noaa_internal": true,
  "maintainer_name": "Elizabeth Holmes",
  "maintainer_email": "eli.holmes@noaa.gov",
  "background_text": "rCAX is an R client for the [Coordinated Assessments API](https://www.streamnet.org/resources/exchange-tools/rest-api-documentation/). Coordinated Assessments data eXchange (CAX) is developed by the Coordinated Assessments Partnership (CAP). CAP is a collaborative process to efficiently share and provide access to standardized derived information, such as fish population-scale high-level indicators (HLIs) and supporting metrics. Participants in CAP include state fish and wildlife management agencies, tribes, federal agencies such as National Oceanic and Atmospheric Administration Fisheries (NOAA Fisheries) and Bonneville Power Administration (BPA), and others. CAP is co-sponsored by StreamNet and Pacific Northwest Aquatic Monitoring Partnership (PNAMP). Make sure to review the [StreamNet Terms of Use](https://nwfsc-math-bio.github.io/rCAX/articles/terms.html) for these data, the [StreamNet Data Policy](https://www.streamnet.org/resources/exchange-tools/data-agreements/) and the citation information from [StreamNet](https://www.streamnet.org/resources/citing-sn/) and [PNAMP](https://www.pnamp.org/project/data-citation-and-attribution) for database queries.",
  "citation": "https://doi.org/10.5281/zenodo.7402463",
  "references": ["Holmes EE, Williams M (2023). “rCAX: Coordinated Assessments REST API R Client. R package version 1.0.1.” NOAA Fisheries, Northwest Fisheries Science Center, Math Bio Program. [doi:10.5281/zenodo.7402463](https://doi.org/10.5281/zenodo.7402463)."],
  "associated_tools": [
    {
      "name": "pycax",
      "link": "httpNA"
    }
  ],
  "user_organizations": ["NOAA Northwest Fisheries Science Center"],
  "website_link": "https://nwfsc-math-bio.github.io/rCAX",
  "documentation_link": "https://nwfsc-math-bio.github.io/rCAX",
  "source_code_link": "https://github.com/nwfsc-math-bio/rCAX",
  "software_badges": ["[![github](https://img.shields.io/github/v/release/nwfsc-math-bio/rCAX?color=brightgreen&label=GitHub)](https://github.com/nwfsc-math-bio/rCAX/releases/latest)\n[![check-release](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml/badge.svg)](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml)"],
  "toolbox_drawers": ["Fish and Fisheries"],
  "keywords": ["R Package", "Salmon", "Standardized Reporting"],
  "uses_github_releases": true
}
```

**Comment by k-doering-NOAA** [comment]
Thanks @eeholmes! It looks like this is a real tool, so would you like it to be added to the toolbox?

I see you added some additional keywords and I can add them as options. Which would be the top 5 that you would like to use to describe the tool?

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "rCAX: R client for the Coordinated Assessment HLI API",
  "tool_abbreviation": "rCAX",
  "authors": "Elizabeth Holmes and Mari Williams",
  "noaa_internal": true,
  "maintainer_name": "Elizabeth Holmes",
  "maintainer_email": "eli.holmes@noaa.gov",
  "background_text": "rCAX is an R client for the [Coordinated Assessments API](https://www.streamnet.org/resources/exchange-tools/rest-api-documentation/). Coordinated Assessments data eXchange (CAX) is developed by the Coordinated Assessments Partnership (CAP). CAP is a collaborative process to efficiently share and provide access to standardized derived information, such as fish population-scale high-level indicators (HLIs) and supporting metrics. Participants in CAP include state fish and wildlife management agencies, tribes, federal agencies such as National Oceanic and Atmospheric Administration Fisheries (NOAA Fisheries) and Bonneville Power Administration (BPA), and others. CAP is co-sponsored by StreamNet and Pacific Northwest Aquatic Monitoring Partnership (PNAMP). Make sure to review the [StreamNet Terms of Use](https://nwfsc-math-bio.github.io/rCAX/articles/terms.html) for these data, the [StreamNet Data Policy](https://www.streamnet.org/resources/exchange-tools/data-agreements/) and the citation information from [StreamNet](https://www.streamnet.org/resources/citing-sn/) and [PNAMP](https://www.pnamp.org/project/data-citation-and-attribution) for database queries.",
  "citation": "https://doi.org/10.5281/zenodo.7402463",
  "references": ["Holmes EE, Williams M (2023). “rCAX: Coordinated Assessments REST API R Client. R package version 1.0.1.” NOAA Fisheries, Northwest Fisheries Science Center, Math Bio Program. [doi:10.5281/zenodo.7402463](https://doi.org/10.5281/zenodo.7402463)."],
  "associated_tools": [
    {
      "name": "pycax",
      "link": "httpNA"
    }
  ],
  "user_organizations": ["NOAA Northwest Fisheries Science Center"],
  "website_link": "https://nwfsc-math-bio.github.io/rCAX",
  "documentation_link": "https://nwfsc-math-bio.github.io/rCAX",
  "source_code_link": "https://github.com/nwfsc-math-bio/rCAX",
  "software_badges": ["[![github](https://img.shields.io/github/v/release/nwfsc-math-bio/rCAX?color=brightgreen&label=GitHub)](https://github.com/nwfsc-math-bio/rCAX/releases/latest)\n[![check-release](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml/badge.svg)](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml)"],
  "keywords": ["R Package", "Salmon", "Standardized Reporting"],
  "uses_github_releases": true
}
```

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "rCAX: R client for the Coordinated Assessment HLI API",
  "tool_abbreviation": "rCAX",
  "authors": "Elizabeth Holmes and Mari Williams",
  "noaa_internal": true,
  "maintainer_name": "Elizabeth Holmes",
  "maintainer_email": "eli.holmes@noaa.gov",
  "background_text": "rCAX is an R client for the [Coordinated Assessments API](https://www.streamnet.org/resources/exchange-tools/rest-api-documentation/). Coordinated Assessments data eXchange (CAX) is developed by the Coordinated Assessments Partnership (CAP). CAP is a collaborative process to efficiently share and provide access to standardized derived information, such as fish population-scale high-level indicators (HLIs) and supporting metrics. Participants in CAP include state fish and wildlife management agencies, tribes, federal agencies such as National Oceanic and Atmospheric Administration Fisheries (NOAA Fisheries) and Bonneville Power Administration (BPA), and others. CAP is co-sponsored by StreamNet and Pacific Northwest Aquatic Monitoring Partnership (PNAMP). Make sure to review the [StreamNet Terms of Use](https://nwfsc-math-bio.github.io/rCAX/articles/terms.html) for these data, the [StreamNet Data Policy](https://www.streamnet.org/resources/exchange-tools/data-agreements/) and the citation information from [StreamNet](https://www.streamnet.org/resources/citing-sn/) and [PNAMP](https://www.pnamp.org/project/data-citation-and-attribution) for database queries.",
  "citation": "https://doi.org/10.5281/zenodo.7402463",
  "references": ["Holmes EE, Williams M (2023). “rCAX: Coordinated Assessments REST API R Client. R package version 1.0.1.” NOAA Fisheries, Northwest Fisheries Science Center, Math Bio Program. [doi:10.5281/zenodo.7402463](https://doi.org/10.5281/zenodo.7402463)."],
  "associated_tools": [
    {
      "name": "pycax",
      "link": "httpNA"
    }
  ],
  "user_organizations": ["NOAA Northwest Fisheries Science Center"],
  "website_link": "https://nwfsc-math-bio.github.io/rCAX",
  "documentation_link": "https://nwfsc-math-bio.github.io/rCAX",
  "source_code_link": "https://github.com/nwfsc-math-bio/rCAX",
  "software_badges": ["[![github](https://img.shields.io/github/v/release/nwfsc-math-bio/rCAX?color=brightgreen&label=GitHub)](https://github.com/nwfsc-math-bio/rCAX/releases/latest)\n[![check-release](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml/badge.svg)](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml)"],
  "keywords": ["R Package", "Salmon", "Standardized Reporting"],
  "uses_github_releases": true
}
```

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "rCAX: R client for the Coordinated Assessment HLI API",
  "tool_abbreviation": "rCAX",
  "authors": "Elizabeth Holmes and Mari Williams",
  "noaa_internal": true,
  "maintainer_name": "Elizabeth Holmes",
  "maintainer_email": "eli.holmes@noaa.gov",
  "background_text": "rCAX is an R client for the [Coordinated Assessments API](https://www.streamnet.org/resources/exchange-tools/rest-api-documentation/). Coordinated Assessments data eXchange (CAX) is developed by the Coordinated Assessments Partnership (CAP). CAP is a collaborative process to efficiently share and provide access to standardized derived information, such as fish population-scale high-level indicators (HLIs) and supporting metrics. Participants in CAP include state fish and wildlife management agencies, tribes, federal agencies such as National Oceanic and Atmospheric Administration Fisheries (NOAA Fisheries) and Bonneville Power Administration (BPA), and others. CAP is co-sponsored by StreamNet and Pacific Northwest Aquatic Monitoring Partnership (PNAMP). Make sure to review the [StreamNet Terms of Use](https://nwfsc-math-bio.github.io/rCAX/articles/terms.html) for these data, the [StreamNet Data Policy](https://www.streamnet.org/resources/exchange-tools/data-agreements/) and the citation information from [StreamNet](https://www.streamnet.org/resources/citing-sn/) and [PNAMP](https://www.pnamp.org/project/data-citation-and-attribution) for database queries.",
  "citation": "https://doi.org/10.5281/zenodo.7402463",
  "references": ["Holmes EE, Williams M (2023). “rCAX: Coordinated Assessments REST API R Client. R package version 1.0.1.” NOAA Fisheries, Northwest Fisheries Science Center, Math Bio Program. [doi:10.5281/zenodo.7402463](https://doi.org/10.5281/zenodo.7402463)."],
  "associated_tools": [
    {
      "name": "pycax",
      "link": "httpNA"
    }
  ],
  "user_organizations": ["NOAA Northwest Fisheries Science Center"],
  "website_link": "https://nwfsc-math-bio.github.io/rCAX",
  "documentation_link": "https://nwfsc-math-bio.github.io/rCAX",
  "source_code_link": "https://github.com/nwfsc-math-bio/rCAX",
  "software_badges": ["[![github](https://img.shields.io/github/v/release/nwfsc-math-bio/rCAX?color=brightgreen&label=GitHub)](https://github.com/nwfsc-math-bio/rCAX/releases/latest)\n[![check-release](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml/badge.svg)](https://github.com/nwfsc-math-bio/rCAX/actions/workflows/check-release.yaml)"],
  "keywords": ["R Package", "Salmon", "Standardized Reporting"],
  "uses_github_releases": true
}
```

**Comment by eeholmes** [comment]
Hi Kathryn,

Yes this is a real tool. Can you add to the toolbox?

This is maybe for the Protected Species toolbox instead of Fish and Fisheries. The CAX database is for the listed PNW salmonids.

Re the top keywords (some are new). Trying to guess what might be most useful.
"keywords": ["Salmon", "REST API client", "R Package", "West Coast"]

Also I see that for the 
```
 "associated_tools": [
    {
      "name": "pycax",
      "link": "httpNA"
    }
```
there is a link. I will be inputting an on-boarding request for pycax also but I want to get that up on PyPi first.

**Comment by k-doering-NOAA** [comment]
@eeholmes , sounds good!

I see that there is something a little funny going on with the toolbox drawer in the automated generated JSON, it is possible for it to be both in protected species and fish and fisheries. I'll take a look at the action and see what is going on.

Also, this thread is making me realize I need to make it clear to users that editing the first description of the issue will cause the JSON to re-render.

**Comment by k-doering-NOAA** [comment]
Thanks @eeholmes , this request helped me learn something about the onboarding process!

How does this landing page for the tool look? https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/rCAX
If it looks good, I will go ahead and add it to the main website.

**Comment by eeholmes** [comment]
A few comments

* Can I have the logo on the page (the hex)? No worries if it is a hassle.
* Can the full citation be shown with the DOI hot-linked?
* For installation button, it'd be nice to be able to click that and it show the code to install. `remotes:::install_github(etc)`. Again, this is a new feature so don't worry if it's a hassle.
* I think the button to documentation should go to the webpage not the references page. So both webpage and documentation going to same place.
* A button linked to Discussions or Bugs would be good.

**Comment by k-doering-NOAA** [comment]
@eeholmes these are all really good ideas! Like you noted, a lot of these are new features, so I opened them as issues now so I can systematically add them to the toolbox webpages.

I did update the citation and the link to documentation, though. Let me know if you think it is ok to be live, or if there are more changes you would like.

**Comment by eeholmes** [comment]
Looks good! Ready to go live. Thanks!

**Comment by k-doering-NOAA** [comment]
Now available on the website!
