### ISSUE TITLE
Onboarding Request: pycax

### ISSUE THREAD

**Issue by eeholmes** [noaa-fisheries-integrated-toolbox/onboard-and-update#11]
### Active Development

Yes

### Tool name

pycax: Python client for the Coordinated Assessment Program CAX database REST API

### Tool abbreviation

pycax

### Author(s)

Elizabeth Holmes and Mari Williams

### NOAA Internal

Yes

### Maintainer Name

Elizabeth Holmes

### Maintainer Email

eli.holmes@noaa.gov

### Background Text

pycax is a Python client for the [Coordinated Assessments API](https://www.streamnet.org/resources/exchange-tools/rest-api-documentation/). Coordinated Assessments data eXchange (CAX) is developed by the Coordinated Assessments Partnership (CAP). CAP is a collaborative process to efficiently share and provide access to standardized derived information, such as fish population-scale high-level indicators (HLIs) and supporting metrics. Participants in CAP include state fish and wildlife management agencies, tribes, federal agencies such as National Oceanic and Atmospheric Administration Fisheries (NOAA Fisheries) and Bonneville Power Administration (BPA), and others. CAP is co-sponsored by StreamNet and Pacific Northwest Aquatic Monitoring Partnership (PNAMP). Make sure to review the [StreamNet Terms of Use](https://nwfsc-math-bio.github.io/rCAX/articles/terms.html) for these data, the [StreamNet Data Policy](https://www.streamnet.org/resources/exchange-tools/data-agreements/) and the citation information from [StreamNet](https://www.streamnet.org/resources/citing-sn/) and [PNAMP](https://www.pnamp.org/project/data-citation-and-attribution) for database queries.

### Citation

doi:10.5281/zenodo.7855729

### Associated Tools

rCAX https://nwfsc-math-bio.github.io/rCAX/

### User Organizations

NOAA Northwest Fisheries Science Center

### Executable Link

https://pypi.org/project/pycax-client/

### Website Link

https://nwfsc-math-bio.github.io/pycax

### Documentation Link

https://nwfsc-math-bio.github.io/pycax

### Source Code Link

https://github.com/nwfsc-math-bio/pycax

### Software Badges

[![pypi](https://img.shields.io/pypi/v/pycax-client.svg)](https://pypi.python.org/pypi-client/pycax-client)
[![docs](https://github.com/nwfsc-math-bio/pycax/actions/workflows/deploy-docs.yml/badge.svg)](https://nwfsc-math-bio.github.io/pycax)
[![tests](https://github.com/nwfsc-math-bio/pycax/actions/workflows/tests.yml/badge.svg)](https://github.com/nwfsc-math-bio/pycax/actions/workflows/tests.yml)
[![coverage](https://nwfsc-math-bio.github.io/pycax/coverage.svg)](https://nwfsc-math-bio.github.io/pycax/_codecoverage/index.html)
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7855729.svg)](https://doi.org/10.5281/zenodo.7855729)

### Toolbox Drawers

- [ ] Ecosystems
- [X] Fish and Fisheries
- [ ] Human Dimensions
- [X] Protected Species
- [ ] General Modeling and Productivity Tools

### Keywords

- [ ] ADMB
- [ ] Age Structured Model
- [ ] Bayesian Modeling
- [ ] Bycatch
- [ ] C++
- [ ] Calculator
- [ ] Data Exploration
- [ ] Data Limited Method
- [ ] Data Visualization
- [ ] Decision Support Tool
- [ ] Developer Utilities
- [ ] Economics
- [ ] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [ ] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [ ] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [ ] Natural Mortality Model
- [ ] NOAA Branding
- [ ] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [ ] R Package
- [ ] Reference Points Model
- [ ] Risk Assessment Tool
- [X] Salmon
- [ ] Sampling Decision Tool
- [ ] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [ ] Spatial Model
- [ ] Species Distribution Model
- [ ] Standardized Reporting
- [ ] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [ ] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [ ] Web App

### Uses Github Releases

Yes

### Comments

"keywords": ["Salmon", "REST API client", "Python Package", "West Coast"]

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "pycax: Python client for the Coordinated Assessment Program CAX database REST API",
  "tool_abbreviation": "pycax",
  "authors": "Elizabeth Holmes and Mari Williams",
  "noaa_internal": true,
  "maintainer_name": "Elizabeth Holmes",
  "maintainer_email": "eli.holmes@noaa.gov",
  "background_text": "pycax is a Python client for the <a href=\"https://www.streamnet.org/resources/exchange-tools/rest-api-documentation/\">Coordinated Assessments API</a>. Coordinated Assessments data eXchange (CAX) is developed by the Coordinated Assessments Partnership (CAP). CAP is a collaborative process to efficiently share and provide access to standardized derived information, such as fish population-scale high-level indicators (HLIs) and supporting metrics. Participants in CAP include state fish and wildlife management agencies, tribes, federal agencies such as National Oceanic and Atmospheric Administration Fisheries (NOAA Fisheries) and Bonneville Power Administration (BPA), and others. CAP is co-sponsored by StreamNet and Pacific Northwest Aquatic Monitoring Partnership (PNAMP). Make sure to review the <a href=\"https://nwfsc-math-bio.github.io/rCAX/articles/terms.html\">StreamNet Terms of Use</a> for these data, the <a href=\"https://www.streamnet.org/resources/exchange-tools/data-agreements/\">StreamNet Data Policy</a> and the citation information from <a href=\"https://www.streamnet.org/resources/citing-sn/\">StreamNet</a> and <a href=\"https://www.pnamp.org/project/data-citation-and-attribution\">PNAMP</a> for database queries.",
  "citation": "doi:10.5281/zenodo.7855729",
  "associated_tools": [
    {
      "name": "rCAX",
      "link": "https://noaa-fisheries-integrated-toolbox.github.io/rCAX"
    }
  ],
  "user_organizations": ["NOAA Northwest Fisheries Science Center"],
  "executable_link": "https://pypi.org/project/pycax-client/",
  "website_link": "https://nwfsc-math-bio.github.io/pycax",
  "documentation_link": "https://nwfsc-math-bio.github.io/pycax",
  "source_code_link": "https://github.com/nwfsc-math-bio/pycax",
  "software_badges": "https://img.shields.io/pypi/v/pycax-client.svg", "https://github.com/nwfsc-math-bio/pycax/actions/workflows/tests.yml/badge.svg", "https://nwfsc-math-bio.github.io/pycax/coverage.svg"],
  "toolbox_drawers": ["Fish and Fisheries", "Protected Species"],
  "keywords": ["Salmon", "API Client", "Python Package", "West Coast"],
  "uses_github_releases": true
}
```

**Comment by k-doering-NOAA** [comment]
thanks @eeholmes ! I wanted to let you know I saw this come in, but have not had time to work on it just yet

**Comment by k-doering-NOAA** [comment]
@eeholmes , we only allow 3 software badges to be displayed currently - could you chose your top three and put them in a comment on this thread?

**Comment by eeholmes** [comment]
[![pypi](https://img.shields.io/pypi/v/pycax-client.svg)](https://pypi.python.org/pypi-client/pycax-client)
[![tests](https://github.com/nwfsc-math-bio/pycax/actions/workflows/tests.yml/badge.svg)](https://github.com/nwfsc-math-bio/pycax/actions/workflows/tests.yml)
[![coverage](https://nwfsc-math-bio.github.io/pycax/coverage.svg)](https://nwfsc-math-bio.github.io/pycax/_codecoverage/index.html)

**Comment by k-doering-NOAA** [comment]
@eeholmes could you take a look at https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/pycax and see if there is anything you would like to change?

**Comment by eeholmes** [comment]
Only thing I would change is hot-linking the DOI. Otherwise looks great!

**Comment by k-doering-NOAA** [comment]
Great! I added a link to the DOI. The page is now live at https://noaa-fisheries-integrated-toolbox.github.io/pycax
