### ISSUE TITLE
Onboarding Request: PSA (new shiny version)

### ISSUE THREAD

**Issue by nathanvaughan-NOAA** [noaa-fisheries-integrated-toolbox/onboard-and-update#12]
### Active Development

Yes

### Tool name

Productivity and Susceptibility Analysis

### Tool abbreviation

PSA

### Author(s)

Nathan Vaughan, Jason Cope

### NOAA Internal

Yes

### Maintainer Name

Nathan Vaughan

### Maintainer Email

nathan.vaughan@noaa.gov

### Background Text

Productivity-Susceptibility Analysis (PSA) is a semi-quantitative and rapid risk assessment approach described by Patrick et al (2009) that relies on the life history characteristics of a stock (i.e., productivity) and its susceptibility to the fishery in question to estimate its expected vulnerability to depletion. First used to classify differences in bycatch sustainability in the Australian prawn fishery in 2001, this assessment has a long history of use in evaluating fisheries and is recommended by several organizations and work groups as a reasonable approach for determining risk. The productivity and susceptibility of a stock is determined using scores ranging from 1 (low) to 3 (high) for a standardized set of attributes related to each index (productivity = 10; susceptibility = 12). When scoring these attributes, the original Patrick et al approach utilized a single score value, data quality rating, and relative weight for each attribute which were combined to calculate single productivity and susceptibility values for each species. Productivity and susceptibility are used to calculate a single vulnerability score for each stock (vulnerability=sqrt((3-productivity)^2 +(susceptibility-1)^2)). Stocks that receive a low productivity score and high susceptibility score are considered to be at a high risk of becoming depleted, while stocks with a high productivity score and low susceptibility score are considered to be at a low risk of becoming depleted. This tool is an R-Shiny application developed to perform a stochastic Productivity-Susceptability risk analysis. It extends the existing methodology of Patrick et al (2009) by providing the ability to assign a relative weight to each score for each attribute rather than a single value. Bootstrap resampling of scores based on their relative weights is used to define productivity, susceptibility, and vulnerability likelihood distributions. This alternate methodology and shiny application were developed by Dr Nathan Vaughan of Vaughan Analytics supporting NOAA's Southeast Fisheries Science Center in collaboration with Dr Jason Cope of NOAA's Northwest Fisheries Science Center. 

### Citation

https://github.com/nathanvaughan1/PSA

### Online App Link

https://connect.fisheries.noaa.gov/connect/#/apps/b86f06f4-8ee6-43ea-82a6-c04a0de3a074/access

### Source Code Link

https://github.com/nathanvaughan1/PSA

### Toolbox Drawers

- [ ] Ecosystems
- [x] Fish and Fisheries
- [x] Human Dimensions
- [ ] Protected Species
- [ ] General Modeling and Productivity Tools

### Keywords

- [ ] ADMB
- [ ] Age Structured Model
- [ ] Bayesian Modeling
- [ ] Bycatch
- [ ] C++
- [ ] Calculator
- [ ] Data Exploration
- [x] Data Limited Method
- [ ] Data Visualization
- [x] Decision Support Tool
- [ ] Developer Utilities
- [ ] Economics
- [ ] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [x] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [ ] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [ ] Natural Mortality Model
- [ ] NOAA Branding
- [ ] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [ ] R Package
- [ ] Reference Points Model
- [x] Risk Assessment Tool
- [ ] Salmon
- [ ] Sampling Decision Tool
- [x] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [ ] Spatial Model
- [ ] Species Distribution Model
- [ ] Standardized Reporting
- [ ] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [ ] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [x] Web App

### Uses Github Releases

Yes

### Comments

I don't have a reference for the tool, I just added the github link to make the submit issue button happy.  I can do the Zenodo reference you mention if you show me how :)

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "Productivity and Susceptibility Analysis",
  "tool_abbreviation": "PSA",
  "authors": "Nathan Vaughan, Jason Cope",
  "noaa_internal": true,
  "maintainer_name": "Nathan Vaughan",
  "maintainer_email": "nathan.vaughan@noaa.gov",
  "background_text": "Productivity-Susceptibility Analysis (PSA) is a semi-quantitative and rapid risk assessment approach described by Patrick et al (2009) that relies on the life history characteristics of a stock (i.e., productivity) and its susceptibility to the fishery in question to estimate its expected vulnerability to depletion. First used to classify differences in bycatch sustainability in the Australian prawn fishery in 2001, this assessment has a long history of use in evaluating fisheries and is recommended by several organizations and work groups as a reasonable approach for determining risk. The productivity and susceptibility of a stock is determined using scores ranging from 1 (low) to 3 (high) for a standardized set of attributes related to each index (productivity = 10; susceptibility = 12). When scoring these attributes, the original Patrick et al approach utilized a single score value, data quality rating, and relative weight for each attribute which were combined to calculate single productivity and susceptibility values for each species. Productivity and susceptibility are used to calculate a single vulnerability score for each stock (vulnerability=sqrt((3-productivity)^2 +(susceptibility-1)^2)). Stocks that receive a low productivity score and high susceptibility score are considered to be at a high risk of becoming depleted, while stocks with a high productivity score and low susceptibility score are considered to be at a low risk of becoming depleted. This tool is an R-Shiny application developed to perform a stochastic Productivity-Susceptability risk analysis. It extends the existing methodology of Patrick et al (2009) by providing the ability to assign a relative weight to each score for each attribute rather than a single value. Bootstrap resampling of scores based on their relative weights is used to define productivity, susceptibility, and vulnerability likelihood distributions. This alternate methodology and shiny application were developed by Dr Nathan Vaughan of Vaughan Analytics supporting NOAA's Southeast Fisheries Science Center in collaboration with Dr Jason Cope of NOAA's Northwest Fisheries Science Center. ",
  "citation": "https://github.com/nathanvaughan1/PSA",
  "online_app_link": "https://connect.fisheries.noaa.gov/connect/#/apps/b86f06f4-8ee6-43ea-82a6-c04a0de3a074/access",
  "source_code_link": "https://github.com/nathanvaughan1/PSA",
  "uses_github_releases": true
}
```

**Comment by k-doering-NOAA** [comment]
@nathanvaughan-NOAA, thanks! Could you check off any toolbox drawers or up to 5 keywords that are appropriate for the tool? I added a few, but I can remove them.

In the meantime, here is a preview of the page: https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/PSA Let me know if you would like to change anything.

**Comment by k-doering-NOAA** [comment]
@shcaba feel free to provide feedback on the preview if you have time (no worries if not): https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/PSA

**Comment by nathanvaughan-NOAA** [comment]
@k-doering-NOAA  weird I checked a bunch of those when I created the issue but they have disappeared. I did get bumped to the Zendo page and then clicked back to the submission so maybe that erased them and I didn't notice.

**Comment by k-doering-NOAA** [comment]
Hmm, interesting! I can see them now, though, so I'll add them, thanks for rechecking.

**Comment by nathanvaughan-NOAA** [comment]
@k-doering-NOAA also looks like it reset the GitHub releases option to yes which should have been a no.

**Comment by nathanvaughan-NOAA** [comment]
Yep, I just reselected them.

**Comment by k-doering-NOAA** [comment]
Ok, fixed the github releases one - sorry for the hiccup with the form, it hasn't gotten a lot of use yet, so I'm open to suggestions if you found anything else to not be working. 

The webpage should have the keywords now https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/PSA

Let me know if it looks good or needs changes.

**Comment by nathanvaughan-NOAA** [comment]
Thanks @k-doering-NOAA that looks good to me.

**Comment by k-doering-NOAA** [comment]
I forgot to mention, I created a nicer URL for the shiny app: https://connect.fisheries.noaa.gov/psa/ . I'll add PSA to the toolbox since @nathanvaughan-NOAA says it looks good, but changes can always be made later if @shcaba finds anything.

**Comment by nathanvaughan-NOAA** [comment]
Thanks @k-doering-NOAA I knew that is what they were supposed to be like but I had forgotten how to make those links for the connect apps. Also, I don't think there was anything wrong with the issue form it was just me leaving the page and then using the browser back button. I assumed it would delete everything I had written but when it kept the text inputs I didn't look further and notice that the tabs and radio buttons had reset.

**Comment by k-doering-NOAA** [comment]
Ah, I see! Maybe I should put a note in the form.

Also, see this for the vanity URLS: https://docs.posit.co/connect/admin/content-management/#vanity-paths

**Comment by shcaba** [comment]
Hi Kathryn-- the preview looks good to me. Thank you!
