### ISSUE TITLE
Onboarding Request: phylosem

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [noaa-fisheries-integrated-toolbox/onboard-and-update#14]
### Active Development

Yes

### Tool name

phylosem

### Tool abbreviation

phylosem

### Author(s)

James Thorson and Wouter van der Bijl

### NOAA Internal

Yes

### Maintainer Name

James Thorson

### Maintainer Email

James.Thorson@noaa.gov

### Background Text

phylosem is a user-friendly and minimal R-package for phylogenetic structural equation models (PSEM).  PSEM generalizes a wide range of methods including phylogenetic generalized linear models, phylologenetic trait imputation, and structural equation models.  PSEM can be used to estimate continuous and categorical traits (e.g., demographic parameters, ecological role, mophometric measurements) for species based on evolutionary trade-offs and measurements for related taxa.  Package phylosem is intended as a simplified alternative to R-package FishLife. 

### Citation

Thorson, J. T., & van der Bijl, W. (In review). phylosem: A fast and simple R package for phylogenetic inference and trait imputation using phylogenetic structural equation models. Journal of Evolutionary Biology.

### References

Thorson, J. T., & van der Bijl, W. (In review). phylosem: A fast and simple R package for phylogenetic inference and trait imputation using phylogenetic structural equation models. Journal of Evolutionary Biology.

Thorson, J. T., Maureaud, A. A., Frelat, R., Mérigot, B., Bigman, J. S., Friedman, S. T., Palomares, M. L. D., Pinsky, M. L., Price, S. A., & Wainwright, P. (2023). Identifying direct and indirect associations among traits by merging phylogenetic comparative methods and structural equation models. Methods in Ecology and Evolution, 14(5), 1259–1275. https://doi.org/10.1111/2041-210X.14076

### Associated Tools

FishLife https://github.com/James-Thorson-NOAA/FishLife

### User Organizations

Alaska Fisheries Science Center

### Online App Link

NA

### Executable Link

install.packages("phylosem")

### Website Link

https://cran.r-project.org/web/packages/phylosem/index.html

### Documentation Link

https://github.com/James-Thorson-NOAA/phylosem/tree/main/vignettes

### Source Code Link

https://github.com/James-Thorson-NOAA/phylosem/

### PDF Download Link

NA

### Toolbox Drawers

- [ ] Ecosystems
- [X] Fish and Fisheries
- [ ] Human Dimensions
- [ ] Protected Species
- [X] General Modeling and Productivity Tools

### Keywords

- [ ] ADMB
- [ ] Age Structured Model
- [ ] Bayesian Modeling
- [ ] Bycatch
- [ ] C++
- [ ] Calculator
- [ ] Data Exploration
- [ ] Data Limited Method
- [ ] Data Visualization
- [ ] Decision Support Tool
- [ ] Developer Utilities
- [ ] Economics
- [ ] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [ ] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [ ] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [X] Natural Mortality Model
- [ ] NOAA Branding
- [ ] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [X] R Package
- [ ] Reference Points Model
- [ ] Risk Assessment Tool
- [ ] Salmon
- [ ] Sampling Decision Tool
- [ ] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [ ] Spatial Model
- [ ] Species Distribution Model
- [ ] Standardized Reporting
- [ ] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [X] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [ ] Web App

### Uses Github Releases

Yes

### Comments

Thanks for developing a helpful and efficient process!

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "phylosem",
  "tool_abbreviation": "phylosem",
  "authors": "James Thorson and Wouter van der Bijl",
  "noaa_internal": true,
  "maintainer_name": "James Thorson",
  "maintainer_email": "James.Thorson@noaa.gov",
  "background_text": "phylosem is a user-friendly and minimal R-package for phylogenetic structural equation models (PSEM).  PSEM generalizes a wide range of methods including phylogenetic generalized linear models, phylologenetic trait imputation, and structural equation models.  PSEM can be used to estimate continuous and categorical traits (e.g., demographic parameters, ecological role, mophometric measurements) for species based on evolutionary trade-offs and measurements for related taxa.  Package phylosem is intended as a simplified alternative to R-package FishLife. ",
  "citation": "Thorson, J. T., & van der Bijl, W. (In review). phylosem: A fast and simple R package for phylogenetic inference and trait imputation using phylogenetic structural equation models. Journal of Evolutionary Biology.",
  "references": ["Thorson, J. T., & van der Bijl, W. (In review). phylosem: A fast and simple R package for phylogenetic inference and trait imputation using phylogenetic structural equation models. Journal of Evolutionary Biology."],
  "associated_tools": [
    {
      "name": "FishLife",
      "link": "https://github.com/James-Thorson-NOAA/FishLife"
    }
  ],
  "user_organizations": ["Alaska Fisheries Science Center"],
  "online_app_link": "NA",
  "executable_link": "install.packages(\"phylosem\")",
  "website_link": "https://cran.r-project.org/web/packages/phylosem/index.html",
  "documentation_link": "https://github.com/James-Thorson-NOAA/phylosem/tree/main/vignettes",
  "source_code_link": "https://github.com/James-Thorson-NOAA/phylosem/",
  "pdf_download_link": "NA",
  "toolbox_drawers": ["Fish and Fisheries", "General Modeling and Productivity Tools"],
  "keywords": ["Natural Mortality Model", "R Package", "TMB"],
  "uses_github_releases": true
}
```

**Comment by k-doering-NOAA** [comment]
Thanks so much! Does this [preview of the phylosem page](https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/phylosem) look ok? Let me know if there is anything that needs to be fixed.

I also added a [link to phylosem](https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/FishLife) from the FishLife toolbox page. (note the link does not currently work, but will when I push the changes to the production site)

If it looks ok, I'll push the changes to production so that phylosem appears on the main toolbox page!

**Comment by James-Thorson-NOAA** [comment]
Thanks!  looks great :)

**Comment by k-doering-NOAA** [comment]
Thanks, I pushed the changes, so it is live! https://noaa-fisheries-integrated-toolbox.github.io/phylosem

**Comment by James-Thorson-NOAA** [comment]
awesome thanks again!
