### ISSUE TITLE
Onboarding Request: EcoCast

### ISSUE THREAD

**Issue by HeatherWelch** [noaa-fisheries-integrated-toolbox/onboard-and-update#15]
### Active Development

No

### Tool name

EcoCast

### Tool abbreviation

EcoCast

### Author(s)

Heather Welch, Elliott Hazen, Kylie Scales

### NOAA Internal

Yes

### Maintainer Name

Heather Welch

### Maintainer Email

Heather Welch

### Background Text

This repository contains code to operationalize EcoCast - a real-time data tool to help fishers and managers allocate fishing effort to optimize the harvest of target fish while minimizing bycatch of protected species. The EcoCast Map product combines the predicted distributions of target catch species and bycatch species into a single map that suggests better and poorer locations to fish off the US West Coast.

### Citation

https://www.science.org/doi/10.1126/sciadv.aar3001

### References

https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.13281
https://conbio.onlinelibrary.wiley.com/doi/full/10.1111/cobi.13417
https://www.sciencedirect.com/science/article/pii/S0034425720301231

### Website Link

https://coastwatch.pfeg.noaa.gov/ecocast/

### Toolbox Drawers

- [X] Ecosystems
- [X] Fish and Fisheries
- [ ] Human Dimensions
- [X] Protected Species
- [ ] General Modeling and Productivity Tools

### Keywords

- [ ] ADMB
- [ ] Age Structured Model
- [ ] Bayesian Modeling
- [X] Bycatch
- [ ] C++
- [ ] Calculator
- [ ] Data Exploration
- [ ] Data Limited Method
- [ ] Data Visualization
- [X] Decision Support Tool
- [ ] Developer Utilities
- [ ] Economics
- [ ] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [X] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [X] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [ ] Natural Mortality Model
- [ ] NOAA Branding
- [X] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [ ] R Package
- [ ] Reference Points Model
- [ ] Risk Assessment Tool
- [ ] Salmon
- [ ] Sampling Decision Tool
- [ ] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [ ] Spatial Model
- [ ] Species Distribution Model
- [ ] Standardized Reporting
- [ ] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [ ] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [X] Web App

### Uses Github Releases

No

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": false,
  "tool_name": "EcoCast",
  "tool_abbreviation": "EcoCast",
  "authors": "Heather Welch, Elliott Hazen, Kylie Scales",
  "noaa_internal": true,
  "maintainer_name": "Heather Welch",
  "maintainer_email": "Heather Welch",
  "background_text": "This repository contains code to operationalize EcoCast - a real-time data tool to help fishers and managers allocate fishing effort to optimize the harvest of target fish while minimizing bycatch of protected species. The EcoCast Map product combines the predicted distributions of target catch species and bycatch species into a single map that suggests better and poorer locations to fish off the US West Coast.",
  "citation": "https://www.science.org/doi/10.1126/sciadv.aar3001",
  "references": ["https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.13281", "", "https://conbio.onlinelibrary.wiley.com/doi/full/10.1111/cobi.13417", "", "https://www.sciencedirect.com/science/article/pii/S0034425720301231"],
  "website_link": "https://coastwatch.pfeg.noaa.gov/ecocast/",
  "toolbox_drawers": ["Ecosystems", "Fish and Fisheries", "Protected Species"],
  "keywords": ["Bycatch", "Decision Support Tool", "Fisheries", "Marine Mammals", "North Pacific", "Web App"],
  "uses_github_releases": false
}
```

**Comment by k-doering-NOAA** [comment]
Preview page for Ecocast: https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/EcoCast

let me know if you would like any edits or if it looks ok!
