### ISSUE TITLE
Onboarding Request: Top Predator Watch

### ISSUE THREAD

**Issue by HeatherWelch** [noaa-fisheries-integrated-toolbox/onboard-and-update#16]
### Active Development

No

### Tool name

Top Predator Watch

### Tool abbreviation

TPW

### Author(s)

Heather Welch

### NOAA Internal

Yes

### Maintainer Name

Heather Welch

### Maintainer Email

heather.welch@noaa.gov

### Background Text

This repository contains code to operationalize Top Predator Watch - a dynamic ocean management tool that produces daily predictions of the distributions of 14 top predator species: blue (Prionace glauca), mako (Isurus oxyrinchus), white (Carcharodon carcharias), and salmon (Lamna ditropis) sharks; albacore (Thunnus alalunga), yellowfin (T. albacares), and bluefin (T. thynnus) tunas; blue whales (Balaenoptera musculus), sooty shearwaters (Ardenna grisea), California sea lions (Zalophus californianus), black-footed (Phoebastria nigripes) and Laysan (P. immutabilis) albatross; elephant seals (Mirounga angustirostris) and leatherback turtles (Dermochelys coriacea). From these predictions we extract core habitat – the locations where each species is most likely to be found based on current environmental conditions. The map above shows core habitat summed across the 14 species, e.g. a value of 2 indicates core habitat for two out of 14 species. It can be interpreted as where top predator density is highest each day.

### Citation

https://www.nature.com/articles/s41467-023-40849-y

### Website Link

https://oceanview.pfeg.noaa.gov/top-predator-watch/

### Toolbox Drawers

- [X] Ecosystems
- [ ] Fish and Fisheries
- [ ] Human Dimensions
- [X] Protected Species
- [ ] General Modeling and Productivity Tools

### Keywords

- [ ] ADMB
- [ ] Age Structured Model
- [ ] Bayesian Modeling
- [X] Bycatch
- [ ] C++
- [ ] Calculator
- [ ] Data Exploration
- [ ] Data Limited Method
- [ ] Data Visualization
- [ ] Decision Support Tool
- [ ] Developer Utilities
- [ ] Economics
- [X] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [X] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [X] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [ ] Natural Mortality Model
- [ ] NOAA Branding
- [X] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [ ] R Package
- [ ] Reference Points Model
- [ ] Risk Assessment Tool
- [ ] Salmon
- [ ] Sampling Decision Tool
- [ ] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [ ] Spatial Model
- [X] Species Distribution Model
- [ ] Standardized Reporting
- [ ] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [ ] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [ ] Web App

### Uses Github Releases

No

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Thanks @HeatherWelch ! Here is a preview view of the Top predator watch page: https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/TPW

I did add the github repository link to the page, and made some minor text edits. Feel free to let me know if you would like anything changed! If it looks good, I can go ahead and publish the page on the FIT website.

I'll post the links to preview changes for each tool on their respective issues.
