### ISSUE TITLE
Update Request: FishSET-Map-Viewer (FishSET_Map_Viewer)

### ISSUE THREAD

**Issue by lpfeif** [noaa-fisheries-integrated-toolbox/onboard-and-update#21]
### Please provide the tool name

FishSET-Map-Viewer (FishSET_Map_Viewer)

### Description

Recommend removing this tool. It hasn't been updated in 5 years and the author is no longer with the agency. I took over development of the FishSET tool last year and we'll have something to onboard as soon as we switch to github enterprise, so soon. 

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
@lpfeif thanks! I removed the tool from the toolbox webpage. What should be done with the [repository](https://github.com/nmfs-fish-tools/FishSET-Map-Viewer)? Perhaps it should be migrated to where the other fish set tools live? It could also be ["archived"](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories#about-repository-archival) to make it clear that future contributions won't be made to it.

**Comment by lpfeif** [comment]
@k-doering-NOAA The new map viewer will be part of the full fishset package. It should already be full archived (built upon in our repository). This "map viewer" was just separated out because it was functional without the rest of the package. I can check with my developer to see if there's anything in it he wants.

**Comment by k-doering-NOAA** [comment]
Oh, I see, thanks for explaining! If the changes are already incorporated in the full fish set, it can probably just be deleted. Let me know when you hear back from your developer to double check.
