### ISSUE TITLE
Onboarding Request: FIMS

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [noaa-fisheries-integrated-toolbox/onboard-and-update#23]
### Active Development

Yes

### Move source code

No

### Tool name

The Fisheries Integrated Modeling System

### Tool abbreviation

FIMS

### Author(s)

Christine Stawitz, Andrea Havron, Matthew Supernaw, Bai Li, Kathryn Doering

### Contributor(s)

Nathan Vaughan, Megumi Oshima, Ian Taylor, Kyle Shertzer, Kelli Johnson, Cole Monnahan, Chris Legault, Kristan Blackhart, Patrick Lynch, Rick Methot, Tim Miller, Huihua Lee, EJ Dick, Peter Kuriyama, Jon Brodziak

### Tool logo

https://github.com/NOAA-FIMS/noaa-fims.github.io/blob/main/assets/img/logo.png

### NOAA Internal

Yes

### Maintainer Name

Christine Stawitz

### Maintainer Email

christine.stawitz@noaa.gov

### Background Text

The NOAA Fisheries Integrated Modeling System is a software system designed and architected to support next-generation fisheries stock assessment, ecosystem, and socioeconomic modeling. A team of experts within NOAA Fisheries is designing and developing the system, and we are advised by the FIMS Council which includes academic, industry, and international partners. We have an operational software system that was released to the public in 2023 and is ready for beta testing, although it is still under active development. Users and developers are welcome to submit feedback using Github issues. 

### Citation

https://doi.org/10.5281/zenodo.10393209

### References

https://zenodo.org/doi/10.5281/zenodo.10393209

### User Organizations

https://ror.org/04950b532

### Documentation Link

https://noaa-fims.github.io/FIMS/

### Source Code Link

https://github.com/FIMS/FIMS

### Software Badges

https://github.com/NOAA-FIMS/FIMS/workflows/call-r-cmd-check/badge.svg
https://codecov.io/gh/NOAA-FIMS/FIMS/branch/main/graph/badge.svg
https://img.shields.io/badge/lifecycle-experimental-orange.svg

### Installation instructions

The following software is required:
* R version 4.0.0 or newer (or RStudio version 1.2.5042 or newer)
the remotes R package
* TMB version 1.8.0 or newer (install instructions are [here](https://github.com/kaskr/adcomp/wiki/Download).)
**Windows Users**
* Rtools4 (available from [here](https://cran.r-project.org/bin/windows/Rtools/rtools40.html))
```
remotes::install_github("NOAA-FIMS/FIMS")
library(FIMS)
```

### Toolbox Drawers

- [ ] Ecosystems
- [X] Fish and Fisheries
- [ ] Human Dimensions
- [ ] Protected Species
- [ ] General Modeling Tools
- [ ] Utility Tools

### Keywords

- [ ] ADMB
- [X] Age Structured Model
- [ ] Bayesian Modeling
- [ ] Bycatch
- [X] C++
- [ ] Calculator
- [ ] Data Exploration
- [ ] Data Limited Method
- [ ] Data Visualization
- [ ] Decision Support Tool
- [ ] Developer Utilities
- [ ] Economics
- [ ] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [ ] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [ ] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [ ] Natural Mortality Model
- [ ] NOAA Branding
- [ ] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [X] R Package
- [ ] Reference Points Model
- [ ] Risk Assessment Tool
- [ ] Salmon
- [ ] Sampling Decision Tool
- [ ] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [ ] Spatial Model
- [ ] Species Distribution Model
- [ ] Standardized Reporting
- [X] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [X] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [ ] Web App

### Uses Github Releases

Yes

### Static version number

0.2.0

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "The Fisheries Integrated Modeling System",
  "tool_abbreviation": "FIMS",
  "authors": "Christine Stawitz, Andrea Havron, Matthew Supernaw, Bai Li, Kathryn Doering",
  "contributors": "Nathan Vaughan, Megumi Oshima, Ian Taylor, Kyle Shertzer, Kelli Johnson, Cole Monnahan, Chris Legault, Kristan Blackhart, Patrick Lynch, Rick Methot, Tim Miller, Huihua Lee, EJ Dick, Peter Kuriyama, Jon Brodziak",
  "tool_logo": "https://github.com/NOAA-FIMS/noaa-fims.github.io/blob/main/assets/img/logo.png",
  "noaa_internal": true,
  "maintainer_name": "Christine Stawitz",
  "maintainer_email": "christine.stawitz@noaa.gov",
  "background_text": "The NOAA Fisheries Integrated Modeling System is a software system designed and architected to support next-generation fisheries stock assessment, ecosystem, and socioeconomic modeling. A team of experts within NOAA Fisheries is designing and developing the system, and we are advised by the FIMS Council which includes academic, industry, and international partners. We have an operational software system that was released to the public in 2023 and is ready for beta testing, although it is still under active development. Users and developers are welcome to submit feedback using Github issues. ",
  "citation": "https://doi.org/10.5281/zenodo.10393209",
  "references": ["https://zenodo.org/doi/10.5281/zenodo.10393209"],
  "user_organizations": ["https://ror.org/04950b532"],
  "documentation_link": "https://noaa-fims.github.io/FIMS/",
  "source_code_link": "https://github.com/FIMS/FIMS",
  "software_badges": ["https://github.com/NOAA-FIMS/FIMS/workflows/call-r-cmd-check/badge.svg\nhttps://codecov.io/gh/NOAA-FIMS/FIMS/branch/main/graph/badge.svg\nhttps://img.shields.io/badge/lifecycle-experimental-orange.svg"],
  "installation_instructions": "The following software is required:\n* R version 4.0.0 or newer (or RStudio version 1.2.5042 or newer)\nthe remotes R package\n* TMB version 1.8.0 or newer (install instructions are [here](https://github.com/kaskr/adcomp/wiki/Download).)\n**Windows Users**\n* Rtools4 (available from [here](https://cran.r-project.org/bin/windows/Rtools/rtools40.html))\n```\nremotes::install_github(\"NOAA-FIMS/FIMS\")\nlibrary(FIMS)\n```",
  "toolbox_drawers": ["Fish and Fisheries"],
  "keywords": ["Age Structured Model", "C++", "R Package", "Stock Assessment Model", "TMB"],
  "uses_github_releases": true,
  "static_version_number": "0.2.0"
}
```

**Comment by MargaretSiple-NOAA** [comment]
This is my drawer, so I'm going to follow this thread -- I got too eager and asked to be assigned and that is not necessary! Kathryn says we're just onboarding as usual.

**Comment by k-doering-NOAA** [comment]
@ChristineStawitz-NOAA could you check and see if there are any changes you would like to this [preview of the FIMS page](https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/FIMS)?

**Comment by ChristineStawitz-NOAA** [comment]
Thank you, @k-doering-NOAA ! Looks great to me.

**Comment by k-doering-NOAA** [comment]
Thanks @ChristineStawitz-NOAA (and @MargaretSiple-NOAA!) 

FIMS has been onboarded: https://noaa-fisheries-integrated-toolbox.github.io/FIMS
