### ISSUE TITLE
Onboarding Request: AgeingError

### ISSUE THREAD

**Issue by iantaylor-NOAA** [noaa-fisheries-integrated-toolbox/onboard-and-update#24]
### Active Development

Yes

### Move source code

No

### Tool name

AgeingError

### Tool abbreviation

NA

### Author(s)

Andre E. Punt, Kelli F. Johnson, James T. Thorson, Ian G. Taylor, Paul Burch

### Contributor(s)

Ian J. Stewart, Melissa A. Haltuch

### NOAA Internal

Yes

### Maintainer Name

Ian Taylor

### Maintainer Email

ian.taylor@noaa.gov

### Background Text

The AgeingError package estimates uncertainty in age estimates double-reads of hard structures (e.g., otoliths) based on the method of Punt et al. (2008) that account for both ageing bias and imprecision. The output can be used in Stock Synthesis or other assessment platforms that incorporate ageing error.

### Citation

Users should cite both the R package and the associated 2008 manuscript, both described at  https://pfmc-assessments.github.io/AgeingError/authors.html#citation

### References

https://doi.org/10.1139/F08-111

### User Organizations

https://ror.org/05r7z1k40

### Website Link

https://pfmc-assessments.github.io/AgeingError/

### Documentation Link

https://pfmc-assessments.github.io/AgeingError/articles/getting_started.html

### Source Code Link

https://github.com/pfmc-assessments/AgeingError

### Installation instructions

In R, install from GitHub:
```
# using {remotes}
remotes::install_github("pfmc-assessments/AgeingError")
# using {pak}
pak::pak("pfmc-assessments/AgeingError")
```

### Toolbox Drawers

- [ ] Ecosystems
- [X] Fish and Fisheries
- [ ] Human Dimensions
- [ ] Protected Species
- [ ] General Modeling Tools
- [ ] Utility Tools

### Keywords

- [ ] ADMB
- [ ] Age Structured Model
- [ ] Bayesian Modeling
- [ ] Bycatch
- [ ] C++
- [ ] Calculator
- [X] Data Exploration
- [ ] Data Limited Method
- [ ] Data Visualization
- [ ] Decision Support Tool
- [ ] Developer Utilities
- [ ] Economics
- [ ] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [X] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [ ] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [ ] Natural Mortality Model
- [ ] NOAA Branding
- [ ] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [X] R Package
- [ ] Reference Points Model
- [ ] Risk Assessment Tool
- [ ] Salmon
- [ ] Sampling Decision Tool
- [ ] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [ ] Spatial Model
- [ ] Species Distribution Model
- [ ] Standardized Reporting
- [ ] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [X] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [ ] Web App

### Uses Github Releases

Yes

### Comments

Latest release is out of date so new github release will be soon (after resolving a few lingering issues).

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "AgeingError",
  "tool_abbreviation": "NA",
  "authors": "Andre E. Punt, Kelli F. Johnson, James T. Thorson, Ian G. Taylor, Paul Burch",
  "contributors": "Ian J. Stewart, Melissa A. Haltuch",
  "noaa_internal": true,
  "maintainer_name": "Ian Taylor",
  "maintainer_email": "ian.taylor@noaa.gov",
  "background_text": "The AgeingError package estimates uncertainty in age estimates double-reads of hard structures (e.g., otoliths) based on the method of Punt et al. (2008) that account for both ageing bias and imprecision. The output can be used in Stock Synthesis or other assessment platforms that incorporate ageing error.",
  "citation": "Users should cite both the R package and the associated 2008 manuscript, both described at  https://pfmc-assessments.github.io/AgeingError/authors.html#citation",
  "references": ["https://doi.org/10.1139/F08-111"],
  "user_organizations": ["https://ror.org/05r7z1k40"],
  "website_link": "https://pfmc-assessments.github.io/AgeingError/",
  "documentation_link": "https://pfmc-assessments.github.io/AgeingError/articles/getting_started.html",
  "source_code_link": "https://github.com/pfmc-assessments/AgeingError",
  "installation_instructions": "In R, install from GitHub:\n```\n# using {remotes}\nremotes::install_github(\"pfmc-assessments/AgeingError\")\n# using {pak}\npak::pak(\"pfmc-assessments/AgeingError\")\n```",
  "toolbox_drawers": ["Fish and Fisheries"],
  "keywords": ["Data Exploration", "Fisheries", "R Package", "TMB"],
  "uses_github_releases": true
}
```

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA, how does this preview look? (Edit: forgot link, here it is): https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/AgeingError 

I also just added AgeingError to the [FIT R universe](https://noaa-fisheries-integrated-toolbox.r-universe.dev/builds), so let me know if the install instructions should include how to install from R universe, too (benefits: precompiled packages don't require users to install the toolchain to build R packages locally, so provides a "cran like" experience; faster installation for packages depending on compiled code.)

**Comment by iantaylor-NOAA** [comment]
Looks good to me, thanks for dealing with this so quickly.

I'm happy to have R universe instructions included. I should add those to the AgeingError README and vignette as well, but I can just copy whatever you put into the FIT page.

**Comment by k-doering-NOAA** [comment]
Great, I added the R universe install instructions, too.

Here's the link to the R universe page: https://noaa-fisheries-integrated-toolbox.r-universe.dev/AgeingError

I'll post once more when the Ageing Error page has been pushed to production!

**Comment by k-doering-NOAA** [comment]
Now onboarded! https://noaa-fisheries-integrated-toolbox.github.io/AgeingError
