### ISSUE TITLE
Update Request: eSDM url change

### ISSUE THREAD

**Issue by k-doering-NOAA** [noaa-fisheries-integrated-toolbox/onboard-and-update#25]
### Please provide the tool name

eSDM

### Description

@smwoodman requested the code repository URL be changed to https://github.com/swfsc/eSDM/ 

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
@smwoodman does this preview look ok to you? Feel free to suggest changes. https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/eSDM

Note that it's now possible to add install instructions. I can add this snippet from your readme to the FIT page, if you would like!

You can install the released version of eSDM from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages('eSDM')
```

To install the latest version from [GitHub](https://github.com):

``` r
# install.packages('devtools')
devtools::install_github('smwoodman/eSDM', build_vignettes = TRUE)
```

**Comment by smwoodman** [comment]
Maybe this is elsewhere on the page, but if not then perhaps adding the "You can access the GUI online at https://connect.fisheries.noaa.gov/eSDM. You do not need to have R or RStudio installed to access the GUI online." block too? I'll happily defer to you though if this isn't the right place for that.

But that does look good! Thanks.

**Comment by k-doering-NOAA** [comment]
Sure, I added installation instructions: https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/eSDM

Does that look like what you had in mind? If so, I'll update the eSDM page!

**Comment by smwoodman** [comment]
Looks great! Thanks @k-doering-NOAA
