### ISSUE TITLE
Onboarding Request: Spatial Economics Toolbox for Fisheries (FishSET)

### ISSUE THREAD

**Issue by Paul-Carvalho** [noaa-fisheries-integrated-toolbox/onboard-and-update#27]
### Active Development

Yes

### Move source code

I'd like to discuss this more

### Tool name

Spatial Economics Toolbox for Fisheries

### Tool abbreviation

FishSET

### Author(s)

Lisa Pfeiffer, Paul Carvalho, Anna Abelman, Min-Yang Lee

### Contributor(s)

Alan Haynie, Melanie Harsch, Bryce McManus, Allen Chen, Adam Hayes, Rita Curtis, Corinne Bassin, Doug Lipton, Jordan Watson

### Tool logo

https://github.com/noaa-nwfsc/FishSET/blob/master/docs/fishset_logo.png

### NOAA Internal

Yes

### Maintainer Name

Paul Carvalho

### Maintainer Email

paul.carvalho@noaa.gov

### Background Text

The Spatial Economics Toolbox for Fisheries (FishSET) is a set of tools developed as an R package for organizing and visualizing data; developing, improving and disseminating modeling best practices; and simulating policy scenarios to explore the welfare consequences of management decisions.

### Citation

Pfeiffer, L., Carvalho, P., Abelman, A., Lee, MY., & Haynie, A. (2024). FishSET: Spatial Economics Toolbox for Fisheries. R Package Version 1.0.0.  https://github.com/noaa-nwfsc/FishSET.

### Executable Link

https://github.com/noaa-nwfsc/FishSET/releases/tag/v1.0.0

### Website Link

https://noaa-nwfsc.github.io/FishSET/

### Documentation Link

https://noaa-nwfsc.github.io/FishSET/articles/FishSET_User_Manual.html

### Source Code Link

https://github.com/noaa-nwfsc/FishSET

### Software Badges

https://github.com/noaa-nwfsc/FishSET/actions/workflows/R-CMD-check.yaml/badge.svg, https://github.com/noaa-nwfsc/FishSET/actions/workflows/secretScan.yml/badge.svg, https://img.shields.io/badge/lifecycle-experimental-orange.svg

### Installation instructions

In R, install the 'devtools' R package, then run the following code (enter a blank line when prompted to update packages):
```options (download.file.method = "wininet")```
```devtools::install_github("noaa-nwfsc/FishSET")```

### Toolbox Drawers

- [ ] Ecosystems
- [ ] Fish and Fisheries
- [X] Human Dimensions
- [ ] Protected Species
- [ ] General Modeling Tools
- [ ] Utility Tools

### Keywords

- [ ] ADMB
- [ ] Age Structured Model
- [ ] Bayesian Modeling
- [ ] Bycatch
- [ ] C++
- [ ] Calculator
- [ ] Data Exploration
- [ ] Data Limited Method
- [x] Data Visualization
- [ ] Decision Support Tool
- [ ] Developer Utilities
- [X] Economics
- [ ] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [ ] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [ ] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [ ] Natural Mortality Model
- [ ] NOAA Branding
- [ ] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [X] R Package
- [ ] Reference Points Model
- [ ] Risk Assessment Tool
- [ ] Salmon
- [ ] Sampling Decision Tool
- [X] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [X] Spatial Model
- [ ] Species Distribution Model
- [ ] Standardized Reporting
- [ ] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [ ] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [ ] Web App

### Uses Github Releases

Yes

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Automatically generated JSON for the onboarding request: 
```
{
  "active_development": true,
  "tool_name": "Spatial Economics Toolbox for Fisheries",
  "tool_abbreviation": "FishSET",
  "authors": "Lisa Pfeiffer, Paul Carvalho, Anna Abelman, Min-Yang Lee",
  "contributors": "Alan Haynie, Melanie Harsch, Bryce McManus, Allen Chen, Adam Hayes, Rita Curtis, Corinne Bassin, Doug Lipton, Jordan Watson",
  "tool_logo": "https://github.com/noaa-nwfsc/FishSET/blob/master/docs/fishset_logo.png",
  "noaa_internal": true,
  "maintainer_name": "Paul Carvalho",
  "maintainer_email": "paul.carvalho@noaa.gov",
  "background_text": "The Spatial Economics Toolbox for Fisheries (FishSET) is a set of tools developed as an R package for organizing and visualizing data; developing, improving and disseminating modeling best practices; and simulating policy scenarios to explore the welfare consequences of management decisions.",
  "citation": "Pfeiffer, L., Carvalho, P., Abelman, A., Lee, MY., & Haynie, A. (2024). FishSET: Spatial Economics Toolbox for Fisheries. R Package Version 1.0.0.  https://github.com/noaa-nwfsc/FishSET.",
  "executable_link": "https://github.com/noaa-nwfsc/FishSET/releases/tag/v1.0.0",
  "website_link": "https://noaa-nwfsc.github.io/FishSET/",
  "documentation_link": "https://noaa-nwfsc.github.io/FishSET/articles/FishSET_User_Manual.html",
  "source_code_link": "https://github.com/noaa-nwfsc/FishSET",
  "software_badges": ["https://github.com/noaa-nwfsc/FishSET/actions/workflows/R-CMD-check.yaml/badge.svg", "https://github.com/noaa-nwfsc/FishSET/actions/workflows/secretScan.yml/badge.svg", "https://img.shields.io/badge/lifecycle-experimental-orange.svg"],
  "installation_instructions": "In R, install the 'devtools' R package, then run the following code (enter a blank line when prompted to update packages):\n```options (download.file.method = \"wininet\")```\n```devtools::install_github(\"noaa-nwfsc/FishSET\")```",
  "toolbox_drawers": ["Human Dimensions"],
  "keywords": ["Data Exploration", "Data Visualization", "Decision Support Tool", "Economics", "Fisheries", "Guided User Interface", "R Package", "Shiny", "Simulation", "Socioeconomics", "Spatial Model"],
  "uses_github_releases": true
}
```

**Comment by k-doering-NOAA** [comment]
@Paul-Carvalho thanks for the request! I know @lpfeif is also involved here.

A few questions before onboarding:
1. Could you pick the top 5 keywords to use for FishSET? Feel free to put your selections in a comment, or simply uncheck the ones you don't want to include in the initial form output.
2. An idea for the citation is to use Zenodo to get a DOI: https://zenodo.org/ . However, if you would like to leave the citation information as-is, that is fine as well.

Here is a a preview of what the FishSET page would look like on the FIT: https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/FishSET . Are there any changes you would like?

**Comment by Paul-Carvalho** [comment]
@k-doering-NOAA, I unchecked the keywords in the above form.

A zenodo citation would be great. The FishSET repo is in the nwfsc github organization so it doesn't show up when I connect my github account to zenodo. Maybe I need Eli to create the zenodo citation?

The FishSET page on FIT looks good. One minor change would be to have a new line before "devtools::install_github" in the installation instructions.

Thanks!

**Comment by lpfeif** [comment]
Let's move Alan Haynie from the "contributors" list to last in the "authors" list

I don't see any reason to move the source code, do you @k-doering-NOAA ? (in response to the question on the form)

**Comment by k-doering-NOAA** [comment]
@Paul-Carvalho and @lpfeif Thanks for getting back to me.

Perhaps @eeholmes could chime in about Zenodo? If we want to move forward without Zenodo initially, a request can be put in to change the citation later on the FIT.

@lpfeif, yes, the code is fine where it is.

Here is the preview page, with corrected keywords, installation instruction spacing, and authorship: https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/FishSET . Let me know if there are still additional changes to make, or if it looks good.

I also added FishSET to our FIT R universe: https://noaa-fisheries-integrated-toolbox.r-universe.dev/FishSET . You can learn more about FIT R universe here: https://noaa-fisheries-integrated-toolbox.github.io/resources/noaa%20fit/fit-runiverse/ . I can remove FishSET if you would not like it included, though!

**Comment by lpfeif** [comment]
Struggling with the order of the contributors, let's use alphabetical:
Corinne Bassin, Allen Chen, Rita Curtis, Melanie Harsch,  Adam Hayes, Bryce McManus, Doug Lipton, Jordan Watson

**Comment by k-doering-NOAA** [comment]
ok, just changed to alphabetical, the preview should update in a min or 2! https://noaa-fisheries-integrated-toolbox.github.io/fit-dev/FishSET

**Comment by Paul-Carvalho** [comment]
Looks great! Thanks, @k-doering-NOAA!

**Comment by k-doering-NOAA** [comment]
Ok, I added FishSET to the production website: https://noaa-fisheries-integrated-toolbox.github.io/FishSET

Feel free to re-open this issue or submit an update issue if there are any additional changes you would like made, @Paul-Carvalho and @lpfeif !
