### ISSUE TITLE
 Onboarding Request: Made-up tool

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [noaa-fisheries-integrated-toolbox/onboard-and-update#8]
### Active Development

Yes

### Tool name

A made-up tool!

### Tool abbreviation

MUT

### Author(s)

Margaret Siple

### NOAA Internal

Yes

### Maintainer Name

Margaret Siple

### Maintainer Email

margaret.siple@noaa.gov

### Background Text

Here is some background text!

### Citation

https://doi.org/10.1111/faf.12579

### Software Badges

https://shields.io/category/coverage/azure-devops/coverage/:organization/:project/:definitionId

### Toolbox Drawers

- [ ] Ecosystems
- [X] Fish and Fisheries
- [ ] Human Dimensions
- [ ] Protected Species
- [ ] General Modeling and Productivity Tools

### Keywords

- [ ] ADMB
- [ ] Age Structured Model
- [X] Bayesian Modeling
- [X] Bycatch
- [ ] C++
- [ ] Calculator
- [ ] Data Exploration
- [ ] Data Limited Method
- [ ] Data Visualization
- [ ] Decision Support Tool
- [ ] Developer Utilities
- [ ] Economics
- [ ] Ecosystem
- [ ] Ensemble Modeling
- [ ] Fish Biology
- [ ] Fisheries
- [ ] Gradient Solver
- [ ] Guided User Interface
- [ ] Individual Based Model
- [ ] Legacy Tool
- [ ] Length Structured Model
- [ ] Management Strategy Evaluation
- [ ] Marine Mammals
- [ ] Maximum Likelihood Estimation
- [ ] Model Builder
- [ ] Model Comparision
- [ ] Multispecies Model
- [X] Natural Mortality Model
- [ ] NOAA Branding
- [ ] North Pacific
- [ ] Output Visualization
- [ ] Projection Modeling
- [ ] R Package
- [ ] Reference Points Model
- [ ] Risk Assessment Tool
- [ ] Salmon
- [ ] Sampling Decision Tool
- [ ] Shiny
- [ ] Simulation
- [ ] Size Spectra Model
- [ ] Size Structured Model
- [ ] Socioeconomics
- [ ] Spatial Model
- [ ] Species Distribution Model
- [ ] Standardized Reporting
- [ ] Stock Assessment Model
- [ ] Stock Assessment Projections
- [ ] Stock Assessment Tool
- [ ] Surplus Production Model
- [ ] Tag Data Model
- [ ] Teaching Tool
- [ ] Time Series
- [ ] TMB
- [ ] User Utilities
- [ ] Virtual Population Analysis
- [ ] Visualization
- [X] Web App

### Uses Github Releases

Yes

### Static version number

0.9.0

### Comments

This looks great! I wish I had a tool that I could onboard! Hopefully I will sometime in the next year.

Additional notes/questions that came up as I was looking through the issue template:
- is there support for tools to be transferred to NMFS's (or AFSC's) Posit Connect instance? Should that be done before the author requests onboarding for their tool? If so, maybe that expectation should be mentioned on this form.
- I like that there is an option to add badges, and that authors can choose. Maybe later we can have a convo about whether certain badges are "standard" - i.e., if there are some that will be more valuable to FIT than others. But for now I like that it's up to the authors.
- On the "Initial process completed" slide in the onboarding slidedeck: Change to "differing" or "different"
- Suggest slight modification to the text at the top, "If you want to update an existing tool, or just contact the FIT team, you can [choose a new issue type here.](https://github.com/noaa-fisheries-integrated-toolbox/onboard-and-update/issues/new/choose)

### Code of Conduct

- [X] I agree to follow the FIT's [Code of Conduct](https://github.com/nmfs-fish-tools/Resources/blob/main/CODE_OF_CONDUCT.md)

**Comment by k-doering-NOAA** [comment]
Thanks @MargaretSiple-NOAA ! I'm glad the JSON was generated, that's a good sign. 

Feel free to post any thoughts about the process on this thread! Esp. anything that was confusing and ideas for making it more clear to users.

**Comment by k-doering-NOAA** [comment]
@MargaretSiple-NOAA thanks for the comments! I incorporated all of them except the "slight modification to the text at the top" - unfortunately, that sentence is generated by GitHub and I don't think there is a way for me to edit it.
